### ISSUE TITLE
 chown: invalid user: 'data-www'

### ISSUE THREAD

**Issue by Steinblock** [rolfwessels/docker-simple-nuget-server#1]
https://github.com/rolfwessels/docker-simple-nuget-server/blob/a6292c7a87a957c0702aa579cb2544cea1408812/init.sh#L7

I got the error message

```
nuget-server| update service config
nuget-server| chown: invalid user: 'data-www'
nuget-server| chown: invalid user: 'data-www'
nuget-server | Starting services
nuget-server | Restarting PHP 7.0 FastCGI Process Manager: php-fpm7.0.
nuget-server | Restarting nginx: nginx.
```

followed by

```
nuget-server | 192.168.143.136 - - [19/Mar/2018:14:40:56 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36" "-"
nuget-server | 2018/03/19 14:40:56 [error] 48#48: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /app/inc/db.php:10
nuget-server | Stack trace:
nuget-server | #0 /app/inc/db.php(10): PDO->__construct('sqlite:../db/pa...', NULL, NULL)
nuget-server | #1 /app/inc/db.php(370): DB::init()
nuget-server | #2 /app/inc/core.php(3): require('/app/inc/db.php')
nuget-server | #3 /app/public/index.php(2): require('/app/inc/core.p...')
nuget-server | #4 {main}
nuget-server |   thrown in /app/inc/db.php on line 10" while reading response header from upstream, client: ... server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "...:8091"

```

I think 

```
chown data-www /app/db
chown data-www /app/packagefiles
```

should be changed to `www-data`

**Comment by rolfwessels** [comment]
I just checked my running instance and I don't have that error. 

```
update service config
Starting services
Restarting PHP 7.0 FastCGI Process Manager: php-fpm7.0.
Restarting nginx: nginx.
```
Are you running the dockerhub instance or did you build your own container ?

**Comment by rolfwessels** [comment]
Ok. I see the issue. You are right. I have made an update and there is a new version on dockerhub.

https://hub.docker.com/r/rolfwessels/docker-simple-nuget-server/tags/
